from django.urls import path
from .views import index, login, contact, about,course_details, form
from .views import error, blog, coming_soon, faq, gallery, index2, link, register, single, logout, admin, deleteapply, forgot_pass, otpcheck, newpassword
from .views import showadmin, editadmin, deleteadmin, showcontact, showcomment, showsubscribe, applyform, editapply
from .views import course,Catgry,addtocart,Usrcart,showadmission,Approved,Aprove,Disaprove

urlpatterns = [
    path('', index, name='index'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),
    # path('language/', language, name='language'),
    # path('communication/', communication, name='communication'),
    # path('business/', business, name='business'),
    # path('software/', software, name='software'),
    # path('social_media/', social_media, name='social_media'),
    # path('photography/', photography, name='photography'),
    path('course_details/', course_details, name='course_details'),
    path('form/', form, name='form'),
    path('404/', error, name='404'),
    path('blog/', blog, name='blog'),
    path('coming_soon/', coming_soon, name='coming_soon'),
    path('faq/', faq, name='faq'),
    path('gallery/', gallery, name='gallery'),
    path('index2/', index2, name='index2'),
    path('link/', link, name='link'),
    path('register/', register, name='register'),
    path('single/', single, name='single'),
    path('admin/', admin, name='admin'),
    path('showadmin/', showadmin, name='showadmin'),
    path('editadmin/<int:id>/', editadmin, name='editadmin'),
    path('deleteadmin/<int:id>/', deleteadmin, name='deleteadmin'),
    path('showcontact/', showcontact, name='showcontact'),
    path('showcomment/', showcomment, name='showcomment'),
    path('showsubscribe/', showsubscribe, name='showsubscribe'),
    path('editapply/<int:id>/', editapply, name='editapply'),
    path('applyform/', applyform, name='applyform'),
    path('deleteapply/', deleteapply, name='deleteapply'),
    path('forgot_pass/', forgot_pass, name='forgot_pass'),
    path('otpcheck/', otpcheck, name='otpcheck'),
    path('newpassword/', newpassword, name='newpassword'),
    path('course/',course, name='course'),
    path('catgry/<str:title>/',Catgry, name='catgry'),
    path("addtocart/<int:id>/",addtocart, name='addtocart'),
    path("Usrcart/",Usrcart, name='Usrcart'),
    path("showadmission/<str:Email>/",showadmission, name='showadmission'),
    path("approved/<str:Email>/",Approved, name='approved'),
    path("Aprove/",Aprove, name='Aprove'),
    path("Disaprove/",Disaprove, name='Disaprove'),
]
