# Generated by Django 3.1.5 on 2021-03-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='Payment',
            field=models.CharField(choices=[('Cradit', 'Cradit'), ('Mail', 'Mail'), ('Perschool', 'Perschool')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
