# Generated by Django 3.1.5 on 2021-03-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_admission_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='Payment',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
