# Generated by Django 3.1.5 on 2021-03-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210313_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='Payment',
            field=models.CharField(choices=[('Cradit', 'Cradit'), ('Mail', 'Mail'), ('Perschool', 'Perschool')], max_length=30),
        ),
    ]
