# Generated by Django 3.1.5 on 2021-03-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210313_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='Course',
            field=models.CharField(choices=[('Language', 'Language'), ('Communication', 'Communication'), ('Business', 'Business'), ('Software', 'Software'), ('Social Media', 'Social Media'), ('Photography', 'Photography'), ('Web Designing', 'Web Designing'), ('Web Technology', 'Web Technology'), ('PC Systems', 'PC Systems'), ('IT Foundations', 'IT Foundations'), ('HR Management', 'HR Management'), ('Modeling', 'Modeling'), ('Basic Marketing', 'Basic Marketing')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
