# Generated by Django 3.1.5 on 2021-03-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_admission_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='Country',
            field=models.CharField(choices=[('India', 'India'), ('Canada', 'Canada'), ('USA', 'USA'), ('China', 'China')], max_length=30),
        ),
        migrations.AlterField(
            model_name='admission',
            name='Course',
            field=models.CharField(choices=[('Language', 'Language'), ('Communication', 'Communication'), ('Business', 'Business'), ('Software', 'Software'), ('Social Media', 'Social Media'), ('Photography', 'Photography'), ('Web Designing', 'Web Designing')], max_length=15),
        ),
    ]
