# Generated by Django 3.1.5 on 2021-03-19 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_fqu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_lang', models.CharField(max_length=30)),
                ('Book_price', models.PositiveIntegerField()),
                ('Book_desc', models.CharField(max_length=30)),
                ('Book_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField()),
                ('Price', models.FloatField()),
                ('Books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.cources')),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.registration')),
            ],
        ),
    ]
