# Generated by Django 3.1.5 on 2021-03-19 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_cart_cources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specific_Crc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='cources',
            name='cat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student.specific_crc'),
            preserve_default=False,
        ),
    ]
