# Generated by Django 3.1.7 on 2021-03-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20210319_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='Approved',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
